#!/usr/bin/env sh
# ``. "$(dirname -- "$0")/_/husky.sh"

# echo "reached to commit ...."

# exe=`detect-secret scan`

# if ! [[ $? == 0 ]]; then
#     echo "package not found..."
#     exit 1
# fi

# exit 1

# node test.js $exe
