name: check-branch
on:
  pull_request:
    types:
      - opened
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: if [ ${{ github.head_ref }} == 'main' ]; then echo "HEAD is equal to {main}" && exit 1; fi
      - run: 
         echo ${{ github.ref }}
         echo ${{ github.head_ref }}
         echo ${{ github.base_ref }}
  job2:
    runs-on: ubuntu-latest
    # if: ${{ github.head_ref != 'main'}}
    steps:
      - run: if [ ${{ github.head_ref != 'main'}} ]; then echo "HEAD is not equal to {main}"; fi
      - run:
         echo "HEAD is NOT equal to (main)"
         echo ${{ github.ref }}
         echo ${{ github.head_ref }}
         echo ${{ github.base_ref }}
