name: check-branch
on:
  pull_request:
    types:
      - opened
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.ref }}
      - run: echo ${{ github.head_ref }}
      - run: echo ${{ github.base_ref }}
      - run: if [ ${{github.head_ref}} == "main"]\then\  echo "main branch can not be the head"\  exit 1\  fi
